### ISSUE TITLE
support for passing in a specific time

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/agenda-batch#3]
This might work out of the box, but we should at least test it.  The use case is we only want to send one email a day, so we create a batch for 1am at night.

**Comment by ecwillis** [comment]
The library that agenda uses is only an interval library.... https://github.com/rschmukler/human-interval but I should be able to append this library at least on the batch calls: https://github.com/matthewmueller/date

**Comment by jgallen23** [comment]
are you sure it won't just work?  https://github.com/rschmukler/agenda#schedulewhen-name-data

**Comment by ecwillis** [comment]
Actualy you are probably right. I didn't notice that date.js is in the agenda package.json - i'll write some tests to confirm.

**Comment by ecwillis** [comment]
I tested this for a string like 'tomorrow at 1am' and it worked as expected.

**Comment by jgallen23** [comment]
woot.  What happens when you put 10am when it's 11am, will it automatically do the next day?

**Comment by ecwillis** [comment]
Yup. Pretty smart little library.
